// Shared markdown generator for the refactor prompts the wizard hands
// to the user when it can't deploy their app as-is.
//
// Two callers today:
//   - D5 (REVISIT.md): incompatible local DB → REFACTOR-FOR-FIREBASE.md
//   - C6 (REVISIT.md, planned): hardcoded secrets → REFACTOR-SECRETS.md
//
// The generic template lets us keep the shape consistent across both
// (and any future refactor-prompts we add). The user pastes the file
// into Claude Code (or any AI tool); the AI applies the refactor; the
// user re-runs `./deploy-app`, which re-detects and either continues
// or blocks again with fresh evidence.
//
// Public API:
//
//   generateRefactorPrompt({ kind, title, appName, summary, detected,
//                            whyItMatters, recipe, steps, rerunCommand })
//     → markdown string
//
//   generateDbRefactorPrompt({ appName, framework, drivers, evidence })
//     → markdown string (D5-specific; calls generateRefactorPrompt
//        with the storage-adapter recipe baked in).
//
// The generic helper takes already-formatted strings/arrays so the
// caller controls phrasing; this file is responsible for the overall
// document structure, not the prose.

const DEFAULT_RERUN = "./deploy-app";

function bullets(items) {
  if (!items || items.length === 0) return "_(none)_";
  return items.map(s => `- ${s}`).join("\n");
}

function numbered(items) {
  if (!items || items.length === 0) return "_(no steps generated — re-run the wizard once the refactor is done)_";
  return items.map((s, i) => `${i + 1}. ${s}`).join("\n");
}

// Generic helper. All sections take strings or arrays-of-strings.
// Optional sections fall back to a helpful placeholder.
export function generateRefactorPrompt({
  kind = "refactor",
  title,
  appName,
  summary,
  detected,        // array of strings, each one bullet (e.g. "src/db.js:14 — new Database(...)")
  whyItMatters,    // string (one paragraph)
  recipe,          // string (multi-paragraph markdown describing the recommended approach)
  steps,           // array of strings, each one numbered step
  rerunCommand = DEFAULT_RERUN
} = {}) {
  const parts = [];

  parts.push(`# ${title || "Refactor required before deploy"}`);
  parts.push("");
  if (appName) {
    parts.push(`_App: \`${appName}\` — generated by deploy-toolkit (\`${kind}\`)._`);
    parts.push("");
  }

  if (summary) {
    parts.push(summary.trim());
    parts.push("");
  }

  parts.push("## What we detected");
  parts.push("");
  parts.push(bullets(detected));
  parts.push("");

  parts.push("## Why this matters");
  parts.push("");
  parts.push((whyItMatters ?? "").trim() || "_(no explanation provided)_");
  parts.push("");

  parts.push("## Recipe");
  parts.push("");
  parts.push((recipe ?? "").trim() || "_(no recipe provided)_");
  parts.push("");

  parts.push("## Refactor steps");
  parts.push("");
  parts.push(numbered(steps));
  parts.push("");

  parts.push("## When you're done");
  parts.push("");
  parts.push("Run the deploy wizard again from the app folder:");
  parts.push("");
  parts.push("```bash");
  parts.push(rerunCommand);
  parts.push("```");
  parts.push("");
  parts.push("The wizard will re-inspect the code. If the refactor is clean it");
  parts.push("will pick up where it left off; if anything is still incompatible");
  parts.push("it will block again with fresh detection output.");
  parts.push("");

  return parts.join("\n");
}

// D5-specific wrapper. Bakes in the Firebase-on-Firestore recipe
// (mirroring the storage-adapter pattern used in the stock-monitor
// migration on 2026-05-08) and turns the inspector's evidence list
// into bullet points the prompt's reader can scan.
//
// Inputs:
//   appName    — string, name of the app (for the doc header)
//   framework  — string, e.g. "express" / "vite-react" (used in the
//                recipe blurb to nudge the AI on where to add imports)
//   drivers    — string[], e.g. ["sqlite", "fs-writes"]
//   evidence   — [{file, line, kind, excerpt}], from detect-db-usage
//
export function generateDbRefactorPrompt({ appName, framework, drivers = [], evidence = [] } = {}) {
  const driverList = drivers.length > 0 ? drivers : ["(none — surface scan only)"];

  const detected = [
    `Detected drivers: ${driverList.join(", ")}`,
    ...evidence.slice(0, 20).map(e => `\`${e.file}:${e.line}\` — \`${e.kind}\` → \`${e.excerpt}\``)
  ];

  const whyItMatters = [
    "Firebase Cloud Functions don't have a persistent filesystem and don't",
    "run sqlite, postgres, mysql, or mongodb. Each invocation runs in a",
    "fresh container; the function package directory is read-only outside",
    "`/tmp/`, and `/tmp/` is wiped on cold start. Any data written to a",
    "local file or local DB process disappears between requests.",
    "",
    "Firebase's recommended persistence layer is Firestore — a managed",
    "NoSQL document database accessed through `firebase-admin` from",
    "Cloud Functions and through the Firebase Web SDK from the browser."
  ].join("\n");

  const recipe = [
    "We want to introduce a thin **storage adapter** layer between your",
    "business logic and the database, then swap the adapter implementation",
    "from your current driver to Firestore. The adapter pattern keeps the",
    "call sites of your DB code mostly unchanged.",
    "",
    "Concretely:",
    "",
    "1. Create `functions/src/storage.js` (or wherever your backend code lives).",
    "   Export functions like `getNotes()`, `addNote(body)`, etc. — one per",
    "   query/mutation the app does today.",
    "2. Inside `storage.js`, use Firestore from `firebase-admin`:",
    "   ```js",
    "   const { getFirestore } = require('firebase-admin/firestore');",
    "   const db = getFirestore();",
    "   async function getNotes() {",
    "     const snap = await db.collection('notes').orderBy('createdAt','desc').get();",
    "     return snap.docs.map(d => ({ id: d.id, ...d.data() }));",
    "   }",
    "   async function addNote(body) {",
    "     const ref = await db.collection('notes').add({ body, createdAt: new Date() });",
    "     return { id: ref.id, body };",
    "   }",
    "   module.exports = { getNotes, addNote };",
    "   ```",
    "3. Replace every call site (the lines under \"What we detected\" above)",
    "   with calls to the adapter. Delete the old driver import.",
    "4. Remove the old driver from `functions/package.json`'s `dependencies`",
    "   (sqlite/pg/mysql/mongodb/mongoose/prisma — whatever was there).",
    "5. Add `firebase-admin` if it's not already a dep:",
    "   ```bash",
    "   npm install --prefix functions firebase-admin",
    "   ```",
    "",
    "**Reference implementation:**",
    "[`personal/monitor/src/storage.js`](../../personal/monitor/src/storage.js) — the",
    "stock-monitor project switched from JSON files to Firestore using this same",
    "adapter pattern on 2026-05-08. The structure (one function per query, all",
    "Firestore calls hidden behind the module boundary) is exactly what we want here."
  ].join("\n");

  // Generate one numbered step per evidence entry so the AI tool gets a
  // concrete checklist instead of a generic instruction.
  const evidenceSteps = evidence.slice(0, 20).map(e =>
    `Migrate the call at \`${e.file}:${e.line}\` (\`${e.kind}\`: \`${e.excerpt}\`) to the new storage adapter.`
  );
  const driverSteps = drivers
    .filter(d => d !== "fs-writes")
    .map(d => `Remove \`${d}\` and its companion deps from \`functions/package.json\` (and the root \`package.json\` if present).`);

  const steps = [
    "Read the recipe above.",
    "Create `functions/src/storage.js` with one function per query/mutation.",
    ...evidenceSteps,
    ...driverSteps,
    "Run `npm install --prefix functions firebase-admin` to add the Firestore SDK.",
    "Re-run `./deploy-app` from the app folder; the wizard will re-detect."
  ];

  const summary = framework
    ? `This is a \`${framework}\` app. Some files use a database driver Firebase can't run as-is — see the detected list below.`
    : "Some files use a database driver Firebase can't run as-is — see the detected list below.";

  return generateRefactorPrompt({
    kind: "db-incompat",
    title: "Refactor for Firebase: replace incompatible local DB with Firestore",
    appName,
    summary,
    detected,
    whyItMatters,
    recipe,
    steps
  });
}
