// Shared markdown generator for the refactor prompts the wizard hands
// to the user when it can't deploy their app as-is.
//
// Three callers today:
//   - D5 (REVISIT.md): incompatible local DB → REFACTOR-FOR-FIREBASE.md
//   - C6 (REVISIT.md): hardcoded secrets → REFACTOR-SECRETS.md
//   - (future) auth-scaffolding refactor prompt (A1) reuses the same shape.
//
// The generic template lets us keep the shape consistent across all of
// them. The user pastes the file into Claude Code (or any AI tool); the
// AI applies the refactor; the user re-runs `./deploy-app`, which
// re-detects and either continues or blocks again with fresh evidence.
//
// Public API:
//
//   generateRefactorPrompt({ kind, title, appName, summary, detected,
//                            whyItMatters, recipe, steps, rerunCommand })
//     → markdown string
//
//   generateDbRefactorPrompt({ appName, framework, drivers, evidence })
//     → markdown string (D5-specific; calls generateRefactorPrompt
//        with the storage-adapter recipe baked in).
//
//   generateSecretsRefactorPrompt({ appName, framework, hardcoded, envRefs })
//     → markdown string (C6-specific; .env recipe + redacted hit list).
//
// The generic helper takes already-formatted strings/arrays so the
// caller controls phrasing; this file is responsible for the overall
// document structure, not the prose.

const DEFAULT_RERUN = "./deploy-app";

function bullets(items) {
  if (!items || items.length === 0) return "_(none)_";
  return items.map(s => `- ${s}`).join("\n");
}

function numbered(items) {
  if (!items || items.length === 0) return "_(no steps generated — re-run the wizard once the refactor is done)_";
  return items.map((s, i) => `${i + 1}. ${s}`).join("\n");
}

// Generic helper. All sections take strings or arrays-of-strings.
// Optional sections fall back to a helpful placeholder.
export function generateRefactorPrompt({
  kind = "refactor",
  title,
  appName,
  summary,
  detected,        // array of strings, each one bullet (e.g. "src/db.js:14 — new Database(...)")
  whyItMatters,    // string (one paragraph)
  recipe,          // string (multi-paragraph markdown describing the recommended approach)
  steps,           // array of strings, each one numbered step
  rerunCommand = DEFAULT_RERUN
} = {}) {
  const parts = [];

  parts.push(`# ${title || "Refactor required before deploy"}`);
  parts.push("");
  if (appName) {
    parts.push(`_App: \`${appName}\` — generated by deploy-toolkit (\`${kind}\`)._`);
    parts.push("");
  }

  if (summary) {
    parts.push(summary.trim());
    parts.push("");
  }

  parts.push("## What we detected");
  parts.push("");
  parts.push(bullets(detected));
  parts.push("");

  parts.push("## Why this matters");
  parts.push("");
  parts.push((whyItMatters ?? "").trim() || "_(no explanation provided)_");
  parts.push("");

  parts.push("## Recipe");
  parts.push("");
  parts.push((recipe ?? "").trim() || "_(no recipe provided)_");
  parts.push("");

  parts.push("## Refactor steps");
  parts.push("");
  parts.push(numbered(steps));
  parts.push("");

  parts.push("## When you're done");
  parts.push("");
  parts.push("Run the deploy wizard again from the app folder:");
  parts.push("");
  parts.push("```bash");
  parts.push(rerunCommand);
  parts.push("```");
  parts.push("");
  parts.push("The wizard will re-inspect the code. If the refactor is clean it");
  parts.push("will pick up where it left off; if anything is still incompatible");
  parts.push("it will block again with fresh detection output.");
  parts.push("");

  return parts.join("\n");
}

// D5-specific wrapper. Bakes in the Firebase-on-Firestore recipe
// (mirroring the storage-adapter pattern used in the stock-monitor
// migration on 2026-05-08) and turns the inspector's evidence list
// into bullet points the prompt's reader can scan.
//
// Inputs:
//   appName    — string, name of the app (for the doc header)
//   framework  — string, e.g. "express" / "vite-react" (used in the
//                recipe blurb to nudge the AI on where to add imports)
//   drivers    — string[], e.g. ["sqlite", "fs-writes"]
//   evidence   — [{file, line, kind, excerpt}], from detect-db-usage
//
export function generateDbRefactorPrompt({ appName, framework, drivers = [], evidence = [] } = {}) {
  const driverList = drivers.length > 0 ? drivers : ["(none — surface scan only)"];

  const detected = [
    `Detected drivers: ${driverList.join(", ")}`,
    ...evidence.slice(0, 20).map(e => `\`${e.file}:${e.line}\` — \`${e.kind}\` → \`${e.excerpt}\``)
  ];

  const whyItMatters = [
    "Firebase Cloud Functions don't have a persistent filesystem and don't",
    "run sqlite, postgres, mysql, or mongodb. Each invocation runs in a",
    "fresh container; the function package directory is read-only outside",
    "`/tmp/`, and `/tmp/` is wiped on cold start. Any data written to a",
    "local file or local DB process disappears between requests.",
    "",
    "Firebase's recommended persistence layer is Firestore — a managed",
    "NoSQL document database accessed through `firebase-admin` from",
    "Cloud Functions and through the Firebase Web SDK from the browser."
  ].join("\n");

  const recipe = [
    "We want to introduce a thin **storage adapter** layer between your",
    "business logic and the database, then swap the adapter implementation",
    "from your current driver to Firestore. The adapter pattern keeps the",
    "call sites of your DB code mostly unchanged.",
    "",
    "Concretely:",
    "",
    "1. Create `functions/src/storage.js` (or wherever your backend code lives).",
    "   Export functions like `getNotes()`, `addNote(body)`, etc. — one per",
    "   query/mutation the app does today.",
    "2. Inside `storage.js`, use Firestore from `firebase-admin`:",
    "   ```js",
    "   const { getFirestore } = require('firebase-admin/firestore');",
    "   const db = getFirestore();",
    "   async function getNotes() {",
    "     const snap = await db.collection('notes').orderBy('createdAt','desc').get();",
    "     return snap.docs.map(d => ({ id: d.id, ...d.data() }));",
    "   }",
    "   async function addNote(body) {",
    "     const ref = await db.collection('notes').add({ body, createdAt: new Date() });",
    "     return { id: ref.id, body };",
    "   }",
    "   module.exports = { getNotes, addNote };",
    "   ```",
    "3. Replace every call site (the lines under \"What we detected\" above)",
    "   with calls to the adapter. Delete the old driver import.",
    "4. Remove the old driver from `functions/package.json`'s `dependencies`",
    "   (sqlite/pg/mysql/mongodb/mongoose/prisma — whatever was there).",
    "5. Add `firebase-admin` if it's not already a dep:",
    "   ```bash",
    "   npm install --prefix functions firebase-admin",
    "   ```",
    "",
    "**Reference implementation:**",
    "[`personal/monitor/src/storage.js`](../../personal/monitor/src/storage.js) — the",
    "stock-monitor project switched from JSON files to Firestore using this same",
    "adapter pattern on 2026-05-08. The structure (one function per query, all",
    "Firestore calls hidden behind the module boundary) is exactly what we want here."
  ].join("\n");

  // Generate one numbered step per evidence entry so the AI tool gets a
  // concrete checklist instead of a generic instruction.
  const evidenceSteps = evidence.slice(0, 20).map(e =>
    `Migrate the call at \`${e.file}:${e.line}\` (\`${e.kind}\`: \`${e.excerpt}\`) to the new storage adapter.`
  );
  const driverSteps = drivers
    .filter(d => d !== "fs-writes")
    .map(d => `Remove \`${d}\` and its companion deps from \`functions/package.json\` (and the root \`package.json\` if present).`);

  const steps = [
    "Read the recipe above.",
    "Create `functions/src/storage.js` with one function per query/mutation.",
    ...evidenceSteps,
    ...driverSteps,
    "Run `npm install --prefix functions firebase-admin` to add the Firestore SDK.",
    "Re-run `./deploy-app` from the app folder; the wizard will re-detect."
  ];

  const summary = framework
    ? `This is a \`${framework}\` app. Some files use a database driver Firebase can't run as-is — see the detected list below.`
    : "Some files use a database driver Firebase can't run as-is — see the detected list below.";

  return generateRefactorPrompt({
    kind: "db-incompat",
    title: "Refactor for Firebase: replace incompatible local DB with Firestore",
    appName,
    summary,
    detected,
    whyItMatters,
    recipe,
    steps
  });
}

// C6-specific wrapper. Walks the user through (1) creating a `.env` file
// with placeholders, (2) adding `.env` to `.gitignore`, (3) replacing
// each inline secret with `process.env.X` (server) or
// `import.meta.env.VITE_X` (Vite client), (4) re-running the wizard.
//
// Inputs:
//   appName    — string, used in the header
//   framework  — string, e.g. "vite-react" / "express" — nudges the
//                recipe to mention import.meta.env vs process.env.
//   hardcoded  — [{file, line, kind, prefix, redacted, excerpt, suppressed}]
//                from detectSecretsUsage. Suppressed entries are excluded
//                from the prompt (they're not blocking the deploy).
//   envRefs    — string[] of env-var names already used via process.env.
//
// We DON'T include the actual secret values in the prompt — only the
// redacted display ("sk_live_AbCd…XyZ9") so the user/AI can identify the
// site without leaking the value into the markdown.
export function generateSecretsRefactorPrompt({
  appName,
  framework,
  hardcoded = [],
  envRefs = []
} = {}) {
  // Only the non-suppressed hits make it into the prompt. Suppressed
  // entries (e.g. Firebase web SDK AIza keys) don't block the deploy
  // and shouldn't be in the refactor checklist.
  const blocking = hardcoded.filter(h => !h.suppressed);

  const detected = blocking.length === 0
    ? ["No hardcoded secrets detected — this prompt covers the cleanup steps for env-var hygiene only."]
    : blocking.slice(0, 30).map(h =>
        `\`${h.file}:${h.line}\` — ${kindLabel(h.kind)} → \`${h.redacted}\` (excerpt: \`${h.excerpt}\`)`
      );

  const whyItMatters = [
    "When you deploy your app, anything written as a literal string in",
    "your code ends up in the public JavaScript bundle on the internet.",
    "Anyone with the URL can open the browser's DevTools, hit View Source,",
    "and read those values. For real secrets — Stripe live keys, AWS",
    "credentials, OpenAI/Anthropic API keys, GitHub PATs — that's an",
    "immediate compromise: the attacker can drain your accounts, run up",
    "bills, or pivot into other systems on your behalf.",
    "",
    "Even server-side code ends up tracked in git, where forks, public",
    "repos, and accidental pushes leak the secrets just as effectively.",
    "",
    "The fix is to move every secret into a `.env` file (which you DO NOT",
    "commit), and reference it from code through `process.env.X` or, for",
    "Vite frontends, `import.meta.env.VITE_X`. After the refactor, the",
    "wizard will ask you per-key whether each value is browser-safe or",
    "server-only, and ingest each one into the right place on Firebase."
  ].join("\n");

  const isVite = framework === "vite-react";
  const isNext = framework === "nextjs";

  const clientPrefix = isVite ? "VITE_" : isNext ? "NEXT_PUBLIC_" : "VITE_";
  const clientRef = isVite
    ? "`import.meta.env.VITE_NAME`"
    : isNext
      ? "`process.env.NEXT_PUBLIC_NAME` (frontend) or `process.env.NAME` (server actions / API routes)"
      : "`process.env.NAME`";

  const recipe = [
    "We want to introduce a **.env file** holding every secret your app",
    "references, then replace each inline literal with a runtime lookup.",
    "",
    "Concretely:",
    "",
    "1. Create a `.env` file at the app root (next to your `package.json`).",
    "   Add one line per secret using the SCREAMING_SNAKE_CASE form:",
    "   ```env",
    "   STRIPE_KEY=sk_live_replace-me",
    "   OPENAI_API_KEY=sk-replace-me",
    "   # …one per detected literal",
    "   ```",
    "   Use your real values as the right-hand side. The wizard will",
    "   ingest them on the next run; you DO NOT need to share them",
    "   anywhere else.",
    "",
    "2. Add `.env` to `.gitignore` so the file never lands in version control:",
    "   ```gitignore",
    "   .env",
    "   .env.local",
    "   .env.production",
    "   ```",
    "   (If `.gitignore` doesn't exist yet, create it with the lines above.)",
    "",
    "3. Add a `.env.example` file that lists the variable names with empty",
    "   values, so teammates know what to fill in. Commit `.env.example`:",
    "   ```env",
    "   STRIPE_KEY=",
    "   OPENAI_API_KEY=",
    "   ```",
    "",
    `4. For every site listed under "What we detected" above, replace the`,
    "   inline literal with a runtime lookup:",
    "   - If the call site runs **on the server** (Cloud Functions code in",
    "     `functions/`, anything called from `onRequest`/`onCall`, scripts",
    "     in `server.js`, etc.), use `process.env.NAME`.",
    `   - If the call site runs **in the browser** (your React/Vite/Next.js`,
    `     frontend), use ${clientRef} and prefix the env var with`,
    `     \`${clientPrefix}\` so the bundler exposes it. Be aware: anything`,
    `     prefixed this way is BAKED INTO THE BUNDLE and visible to anyone`,
    `     using your site. Only use the client form for values that are`,
    `     safe to be public (e.g. Firebase Web SDK config keys, public`,
    `     feature-flag URLs).`,
    "",
    "5. Verify nothing else still references the literal value. Search",
    "   the repo for `sk_live_`, `AKIA`, `ghp_`, `sk-ant-`, `xoxb-`, etc.",
    "   and confirm every hit is now reading from env vars.",
    "",
    "6. Re-run `./deploy-app`. The wizard re-scans, confirms the source",
    "   is clean, and asks you per-key whether each env var is",
    "   **browser-safe** or **server-only** so it can put each value in",
    "   the right place on Firebase."
  ].join("\n");

  const secretSteps = blocking.slice(0, 30).map(h =>
    `Replace the literal at \`${h.file}:${h.line}\` (${kindLabel(h.kind)} — \`${h.redacted}\`) with a runtime env-var lookup.`
  );

  const envRefSteps = envRefs.length > 0
    ? [`Make sure each of these env vars (${envRefs.join(", ")}) has a line in \`.env\` (and an empty line in \`.env.example\`).`]
    : [];

  const steps = [
    "Read the recipe above so the substitutions make sense in context.",
    "Create `.env` at the app root with one line per detected secret.",
    "Add `.env` (and `.env.local`/`.env.production`) to `.gitignore`.",
    "Create or update `.env.example` with the variable names (no values).",
    ...secretSteps,
    ...envRefSteps,
    "Re-run `./deploy-app` from the app folder; the wizard will re-detect and continue."
  ];

  const summary = framework
    ? `This is a \`${framework}\` app. We found ${blocking.length} hardcoded secret${blocking.length === 1 ? "" : "s"} that need to move into environment variables before this app is safe to deploy.`
    : `We found ${blocking.length} hardcoded secret${blocking.length === 1 ? "" : "s"} that need to move into environment variables before this app is safe to deploy.`;

  return generateRefactorPrompt({
    kind: "secrets",
    title: "Refactor for Firebase: move hardcoded secrets into environment variables",
    appName,
    summary,
    detected,
    whyItMatters,
    recipe,
    steps
  });
}

// Map our internal kind labels to plain English for the prompt body.
function kindLabel(kind) {
  switch (kind) {
    case "stripe-live": return "Stripe live key";
    case "stripe-test": return "Stripe test key";
    case "aws-access-key": return "AWS access key ID";
    case "aws-secret-key": return "AWS secret access key";
    case "github-pat": return "GitHub personal access token";
    case "github-oauth": return "GitHub OAuth token";
    case "github-user": return "GitHub user token";
    case "anthropic": return "Anthropic API key";
    case "openai": return "OpenAI API key";
    case "slack-bot": return "Slack bot token";
    case "slack-user": return "Slack user token";
    case "google-api-key-maybe-firebase": return "Google API key (possibly Firebase — verify)";
    default: return kind;
  }
}
