// SignInWithGoogle.jsx — generated by deploy-toolkit.
//
// A drop-in "Sign in with Google" button for any Vite-React app.
// Initialises Firebase from the sibling `firebase-config.js` (also
// generated by deploy-toolkit), wires the popup OAuth flow, and
// re-renders when the auth state changes.
//
// Safe to re-run the wizard against this file — the inject-auth stage
// only writes this file when it doesn't already exist. Edit it freely
// after first generation.

import { useEffect, useState } from "react";
import { initializeApp, getApps, getApp } from "firebase/app";
import {
  getAuth,
  GoogleAuthProvider,
  onAuthStateChanged,
  signInWithPopup,
  signOut
} from "firebase/auth";
import { firebaseConfig } from "./firebase-config.js";

// `initializeApp` is not idempotent — calling it twice with the same
// name throws. Vite/React's HMR or a second instance of this component
// would trip that. Use `getApps()` to reuse the default app if one
// already exists.
function ensureFirebaseApp() {
  return getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
}

const btnStyle = {
  display: "inline-flex",
  alignItems: "center",
  gap: 8,
  padding: "10px 18px",
  border: "1px solid #2a2a2a",
  borderRadius: 999,
  background: "#ffa000",
  color: "#1a1300",
  font: "inherit",
  fontWeight: 600,
  fontSize: 14,
  cursor: "pointer"
};

const rowStyle = {
  display: "inline-flex",
  alignItems: "center",
  gap: 10,
  padding: "8px 14px",
  border: "1px solid #2a2a2a",
  borderRadius: 999,
  background: "#1a1a1a",
  color: "#ededed",
  font: "inherit",
  fontSize: 13
};

const linkBtnStyle = {
  background: "transparent",
  color: "#ffa000",
  border: "none",
  padding: 0,
  font: "inherit",
  fontSize: 13,
  cursor: "pointer",
  textDecoration: "underline"
};

export default function SignInWithGoogle() {
  const [user, setUser] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    const auth = getAuth(ensureFirebaseApp());
    return onAuthStateChanged(auth, (u) => setUser(u));
  }, []);

  async function handleSignIn() {
    setError("");
    setBusy(true);
    try {
      const auth = getAuth(ensureFirebaseApp());
      const provider = new GoogleAuthProvider();
      await signInWithPopup(auth, provider);
    } catch (err) {
      // Surface a short error — common one is "popup closed by user"
      // which isn't really an error, so we ignore the auth/popup-closed
      // code instead of shouting at the user.
      if (err && err.code !== "auth/popup-closed-by-user") {
        setError(err.message || String(err));
      }
    } finally {
      setBusy(false);
    }
  }

  async function handleSignOut() {
    setBusy(true);
    try {
      const auth = getAuth(ensureFirebaseApp());
      await signOut(auth);
    } finally {
      setBusy(false);
    }
  }

  if (user) {
    return (
      <div style={rowStyle}>
        <span>Signed in as <strong>{user.email || user.displayName || user.uid}</strong></span>
        <button type="button" onClick={handleSignOut} disabled={busy} style={linkBtnStyle}>
          {busy ? "Signing out…" : "Sign out"}
        </button>
      </div>
    );
  }

  return (
    <div>
      <button type="button" onClick={handleSignIn} disabled={busy} style={btnStyle}>
        <span aria-hidden="true">🔥</span>
        <span>{busy ? "Opening Google…" : "Sign in with Google"}</span>
      </button>
      {error && (
        <div style={{ marginTop: 8, color: "#ff6b6b", fontSize: 12 }}>{error}</div>
      )}
    </div>
  );
}
